### ISSUE TITLE
Add a back button, and improve the UI for the PM Screen. 

### ISSUE THREAD

**Issue by thecount92** [MSPARP/newparp#62] opened 2015-04-15 05:02 UTC
The pm screen is sort of lacking, it needs a better look. a back button to go back to the my chats page, better notifications system and maybe some added functions. anything to you know, make it look and act better.

**Comment by tehdragonfly** [comment] 2015-04-15 13:22
This is pretty much a duplicate of #47.

**Closed by tehdragonfly** 2015-04-15 13:22 UTC
Labels: duplicate, enhancement
